# Site settings
title: Voting Methods Models
description: "Voting Methods Models Working Group publication"
baseurl: "/VotingMethods" # the subpath of your site, e.g. /blog
url: "https://pages.nist.gov/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# GitHub information
org_name: usnistgov
repo_name: VotingMethods

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /VotingMethods/

host: 0.0.0.0
